# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
    push:
        branches:
            - dev
            - KU-**
    pull_request:
        branches:
            - main
            - dev

jobs:
    main:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Flutter SDK
              uses: rexthecoder/Pinky@v2.0.0
              with:
                  filename: kidtalkie.apk
            # - run: flutter --version
            # - run: flutter doctor
            # - run: flutter pub get
            # - run: flutter test
            # - run: flutter build ios --release --no-codesign
            # - name: Build apk
            #   id: buildApp
            #   run: flutter build apk
      
