# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "dev", "KU-**" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.7.7
      - run: flutter --version
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign 
      - run: flutter build apk
